import "pkg:/source/api/sdk.bs"
import "pkg:/source/utils/misc.bs"

sub init()
    m.top.functionName = "loadThemeSongs"
end sub

sub loadThemeSongs()
    if not isValid(m.top.itemId) or m.top.itemId = "" then return

    ' Get theme songs for the item
    response = api.items.GetThemeSongs(m.top.itemId, {})

    if isValid(response) and isValid(response.Items) and response.Items.Count() > 0
        m.top.themeSongs = response
    else
        m.top.themeSongs = invalid
    end if
end sub
