import "pkg:/source/enums/PosterLoadStatus.bs"
import "pkg:/source/utils/misc.bs"

sub init()
    m.profileImage = m.top.findNode("profileImage")
    m.profileImage.observeField("loadStatus", "onPosterLoadStatusChanged")

    m.avatarRing = m.top.findNode("avatarRing")
    m.profileName = m.top.findNode("profileName")
    m.scaleGroup = m.top.findNode("scaleGroup")
end sub

sub onPosterLoadStatusChanged()
    if m.profileImage.loadStatus <> PosterLoadStatus.LOADING
        m.profileImage.unobserveField("loadStatus")
    end if

    if isStringEqual(m.profileImage.loadStatus, PosterLoadStatus.FAILED)
        m.profileImage.uri = "pkg:/images/baseline_person_white_48dp.png"
    end if
end sub

sub onFocusChanged()
    if not isValid(m.top.itemContent) then return

    if m.top.itemHasFocus
        m.avatarRing.blendColor = "0x00A4DCFF"
        m.profileName.color = "0x00A4DCFF"
        m.scaleGroup.scale = [1.08, 1.08]
    else
        m.avatarRing.blendColor = "0x6B728099"
        m.profileName.color = "0xD1D5DBFF"
        m.scaleGroup.scale = [1.0, 1.0]
    end if
end sub

sub itemContentChanged()
    itemData = m.top.itemContent
    if not isValid(itemData) then return

    m.profileName.text = itemData.name

    if itemData.imageURL = ""
        m.profileImage.uri = "pkg:/images/baseline_person_white_48dp.png"
    else
        m.profileImage.uri = itemData.imageURL
    end if
end sub
