import "pkg:/source/utils/misc.bs"
import "pkg:/source/utils/themeApply.bs"

sub init()
    m.header = m.top.findNode("header")
    m.line = m.top.findNode("line")
    m.rowBg = m.top.findNode("rowBg")

    m.header.font.size = 22
    m.line.font.size = 20

    themeApply.ApplyToItem(m.top)
end sub

sub onContentChanged()
    cont = m.top.itemContent
    if not isValid(cont) then return
    m.header.text = cont.title
    m.line.text = cont.description
    m.line.visible = isValidAndNotEmpty(cont.description)
end sub

sub onFocusChanged()
    m.rowBg.visible = m.top.itemHasFocus
end sub
