import "pkg:/source/api/sdk.bs"
import "pkg:/source/utils/config.bs"

sub init()
    m.top.functionName = "getMediaBarData"
end sub

sub getMediaBarData()
    m.top.mediaBarData = api.items.Get({
        userId: m.top.userId,
        includeItemTypes: "Movie,Series",
        recursive: true,
        sortBy: "Random",
        limit: 50,
        filters: "IsNotFolder",
        fields: "Overview,Genres,CommunityRating,OfficialRating,ProductionYear,RunTimeTicks,ProviderIds"
    })
end sub
