import "pkg:/source/api/userauth.bs"
import "pkg:/source/api/baserequest.bs"
import "pkg:/source/utils/config.bs"
import "pkg:/source/utils/misc.bs"

sub init()
    m.top.functionName = "runQuickConnect"
end sub

sub runQuickConnect()
    if isStringEqual(m.top.mode, "initiate")
        initiateQuickConnect()
        return
    end if

    monitorQuickConnect()
end sub

' Runs on the task thread because roUrlTransfer can't be created on the render thread.
sub initiateQuickConnect()
    resp = APIRequest("QuickConnect/Enabled")

    if isStringEqual(getString(resp), "true")
        json = initQuickConnect()
        if isValid(json)
            m.top.initResult = { enabled: true, json: json }
            return
        end if
    end if

    m.top.initResult = { enabled: false }
end sub

sub monitorQuickConnect()
    authenticated = checkQuickConnect(m.top.secret)

    if authenticated = true
        loggedIn = AuthenticateViaQuickConnect(m.top.secret)
        if loggedIn
            session.setRuntimeRequestContextValue("moonfin.authToken", m.global.session.user.authToken)

            currentUser = AboutMe()
            session.user.Login(currentUser, m.top.saveCredentials)
            session.user.LoadUserPreferences()
            LoadUserAbilities()
            m.top.authenticated = 1
            return
        end if
    end if

    m.top.authenticated = -1
end sub
